function standardFields = standardfields()

standardFields = ["x", "y", "h", "xy", "xyh", "h_prob", ...
    "h_vec", "h_score", "rxyh_over_rxy",...
    "centroid", "reference_point", "amplitude", "theta_preference",...
    "goodness_of_fit", "model_output","acceptedSamples", "fracAcceptableDegree", "fracEnoughTime"];
